### ISSUE TITLE
Action overrides @actions/setup-node step, when setup comes after.

### ISSUE THREAD

**Issue by kopepasah** [godaddy-wordpress/setup-wp-env#2]
This Action uses [@actions/setup-node](https://github.com/actions/setup-node) in order to run the install of [@wordpress/env](https://github.com/WordPress/gutenberg/tree/trunk/packages/env) and setup of the environment. Because of this, the Node versions are set to what is provided by this Action, when the Action step comes after another [@actions/setup-node](https://github.com/actions/setup-node) in a workflow.

For example, the following workflow config results in Node version `lts/*` (as of right now is `18`, and is not expected).

```yaml
- name: Setup Node
  uses: actions/setup-node@v3
  with:
    node-version: 16

- name: Setup wp-env
  uses: godaddy-wordpress/setup-wp-env@v1
```

On the other hand, the following workflow config results in Node version `16` (which is expected).

```yaml
- name: Setup wp-env
  uses: godaddy-wordpress/setup-wp-env@v1

- name: Setup Node
  uses: actions/setup-node@v3
  with:
    node-version: 16
```

Because this Action requires node, we must add an input for the user to provide options to [@actions/setup-node](https://github.com/actions/setup-node) config OR do not run [@actions/setup-node](https://github.com/actions/setup-node) when node is already setup.
